### ISSUE TITLE
caption + figure placement

### ISSUE THREAD

**Issue by benkeser** [CoVPN/correlates_reporting#189] opened 2021-03-28 18:07 UTC
In new report builds, the formatting can get a bit gory. 
- there are very small vertical margins 
- Figure captions can be separated from the figures by a page break.

This is a relatively minor issue, but maybe it's a quick fix. Or was this something @nhejazi had to do in order to get the section headings to go to the right spot?

<img width="529" alt="Screen Shot 2021-03-28 at 2 05 44 PM" src="https://user-images.githubusercontent.com/17482713/112762686-f9af9200-8fce-11eb-81ee-64df6d030ad2.png">

**Comment by benkeser** [comment] 2021-03-28 19:24
This actually feels like it needs higher priority. The formatting is very awkward in places.

**Comment by nhejazi** [comment] 2021-03-28 23:05
From some manual `git` bisection, it looks like the formatting issues were introduced by #158, which was intended to fix the section labeling. This is clear from inspecting report builds before/after merging of that PR; for example, in the CoR report:
* before: https://raw.githubusercontent.com/CoVPN/correlates_reporting/d903dff1b767ecde86772b7b7245722f0fa8c850/covpn_correlates_cor.pdf
* after: https://raw.githubusercontent.com/CoVPN/correlates_reporting/906334b986da870da7c32445bcc9358ec2f9a282/covpn_correlates_cor.pdf

**Comment by nhejazi** [comment] 2021-03-28 23:09
#193 endeavors to fix this.

**Comment by nhejazi** [comment] 2021-03-29 03:41
Removal of the `"H"` float option results in a LaTeX error: `! LaTeX Error: Too many unprocessed floats.`, which no combination of other `figure.pos` specifications seem to fix.

**Comment by benkeser** [comment] 2021-03-29 03:42
Yes unfortunately I think that's why we went to `H` in the first place.

**Comment by nhejazi** [comment] 2021-03-29 05:18
Adding `\clearpage` in front of every Rmd chunk in `cor_graphical/report.Rmd` seems to somewhat alleviate this.

How does the formatting in that section of [this build](https://github.com/CoVPN/correlates_reporting/blob/97cffc957cb331a3acc8bf642b1346d766625eb5/covpn_correlates_cor.pdf) look? The (top) margins still seem to small to me but we might be able to fix this easily with an Rmd or bookdown option.

**Comment by benkeser** [comment] 2021-03-29 15:38
The issue with margin seems to be the [use of `newgeometry` here](https://github.com/CoVPN/correlates_reporting/blob/7c008880f69ce78056d522425ab9bae2a596c0b2/immuno_tabular/report.Rmd#L24).

The default in `bookdown` seems to be 
```latex
\usepackage[margin=1in]{geometry}
```

Resetting `newgeometry` at the end of `report.Rmd` should work. Testing now.

**Comment by nhejazi** [comment] 2021-03-29 15:42
Got it, that’s a good catch. The margin call to `geometry` is already set in latex/preamble.tex (even if it weren’t a bookdown default) so it should be sufficient to just undo the `newgeometry` call after the horizontal table, or just remove that call altogether.

**Comment by benkeser** [comment] 2021-03-29 15:43
I think the call is needed to fit the landscape tables on a page. Or I assume so. @cyu-hvtn?

**Comment by nhejazi** [comment] 2021-03-29 15:44
Also, if you could confirm whether the solution with `\clearpage` looks alright in the CoR report, I can just manually add that change throughout the remainder of the report.tex files.

**Comment by benkeser** [comment] 2021-03-29 15:47
Yes, the `\clearpage` looks right. I would go ahead and put it everywhere in `immuno_graphical` and `cor_graphical`

**Comment by cyu-hvtn** [comment] 2021-03-29 15:48
> I think the call to `newgeometry` is needed to fit the landscape tables on a page. Or I assume so. @cyu-hvtn?

Yes, I changed the margins for the landscape tables. I can add some lines to change it back to` \usepackage[margin=1in]{geometry}` at end of my tables

**Comment by benkeser** [comment] 2021-03-29 15:48
> Resetting `newgeometry` at the end of `report.Rmd` should work. Testing now.

This works. I just added line 

```latex
\newgeometry{margin=1in}
```

on the last line of `immuno_tabular/report.Rmd`

**Comment by benkeser** [comment] 2021-03-29 15:49
> I can add some lines to change it back to` \usepackage[margin=1in]{geometry}` at end of my tables

I think @nhejazi will go ahead and add to #195

**Comment by nhejazi** [comment] 2021-03-29 17:51
1d69a3f fixes the `geometry` and `\clearpage` issues. This issue is resolved by #193

**Closed** 2021-03-29 22:18 UTC
Labels: bug, invalid
